### ISSUE TITLE
readme에 있는 내용들을 공부목적 폴더로 옮겼으면 좋겠어요 :)

### ISSUE THREAD

**Issue by ggjae** [Hee-Jae/springboot#2]
들어오자마자 공부하게 되는 그런 느낌인가요?

**Comment by Hee-Jae** [comment]
공부하면서 그때그때 생각나는 궁금한 점들에 대해서 따로 학습해보고 임시로 정리 해놓은 노트입니다^^
어떻게 깔끔하게 정리할지 아직 고민중이에요 ㅇ-ㅇ

**Comment by Hee-Jae** [comment]
내용이 더 추가된 후에 정리하면 골치 아파질까봐 바로 정리했습니다ㅎㅎ
